# Generated by Django 5.0.3 on 2024-04-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'TEACHER'), (3, 'STUDENT')], default=1, max_length=50),
        ),
    ]
