# Generated by Django 5.0.3 on 2024-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feedback',
            name='feedback_reply',
            field=models.TextField(default=' ', null=True),
        ),
    ]
