# Generated by Django 5.0.3 on 2024-04-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
