# Generated by Django 4.1.2 on 2024-04-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_remove_assignment_teacher_delete_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
