# Generated by Django 4.1.2 on 2024-04-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
