# Generated by Django 5.0.3 on 2024-04-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_studentresult'),
        ('students', '0030_notice'),
    ]

    operations = [
    ]
