# Generated by Django 5.0.3 on 2024-04-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_submission_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='file',
            new_name='files',
        ),
    ]
