# Generated by Django 5.0.3 on 2024-04-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_alter_assignment_files_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.FileField(upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
    ]
