# Generated by Django 5.0.3 on 2024-04-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
