# Generated by Django 5.0.3 on 2024-05-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='total_marks',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
